# Generated by Django 6.0.4 on 2026-05-04 17:30

import app1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[app1.validators.positive_integer])),
                ('in_stock', models.BooleanField(default=True)),
                ('available_until', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
